# Generated by Django 4.0.3 on 2022-03-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_neighbourhood_neighbour'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='neighbour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live', to='app_main.neighbourhood'),
        ),
    ]
