# Generated by Django 4.0.3 on 2022-03-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
    ]
