# Generated by Django 4.0.3 on 2022-03-21 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbour',
            field=models.ManyToManyField(blank=True, null=True, related_name='trev', to=settings.AUTH_USER_MODEL),
        ),
    ]
