# Generated by Django 4.0.3 on 2022-03-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_remove_business_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bs_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bs_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bs_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bs_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bs_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bs_updated_at',
            new_name='updated_at',
        ),
    ]
